New Sign In Screen
WrathChaos/react-native-social-login-screen pull request #2
Opened 2021-05-29 19:03 UTC by sevvaleygul0

## What

- New screen is created for sign in.

## Demo

https://user-images.githubusercontent.com/56435142/120082038-56135880-c0c9-11eb-92db-e9080d368b30.mov

<img width="384" alt="Screen Shot 2021-05-29 at 22 00 00" src="https://user-images.githubusercontent.com/56435142/120082073-9a065d80-c0c9-11eb-84b7-2f862bc26f25.png">

2021-05-30 22:21 UTC, WrathChaos requested changes
There should be not local lib in the example

2021-05-30 22:21 UTC, kuraydev commented on lib/SocialLoginScreen.tsx
> +          />
There are too many repetitions for "this.props.". You can use de-construction

2021-05-30 22:21 UTC, kuraydev commented on lib/SocialLoginScreen.tsx
> +            loginText={this.props.loginText}
Can't we just prop drilling instead of set the all of the props.

2021-05-30 22:21 UTC, WrathChaos commented on lib/signUpScreen/SignUpScreen.tsx
> +import * as React from "react";
I think we do not need a username here, we need a password and re-password here

2021-05-30 22:21 UTC, WrathChaos commented on lib/signUpScreen/SignUpScreen.tsx
> +      loginText = "LOG IN",
This is a signup screen, can you change the loginText and all of them to signUp.. Also "LOG IN" should change to "SIGN UP"

2021-05-30 22:21 UTC, WrathChaos commented on lib/signUpScreen/SignUpScreen.tsx
> +  };
This is the signup screen, can you change the "signin" namespace to "signup".

2021-05-30 22:21 UTC, WrathChaos commented on lib/signUpScreen/SignUpScreen.tsx
> +    const { signinTitleText = "Sign In", signinTextStyle } = this.props;
This string should be "Sign Up"

2021-06-01 06:59 UTC, sevvaleygul0 commented
https://user-images.githubusercontent.com/56435142/120279869-a18f5780-c2bf-11eb-965b-12cd01448a4d.mov

2021-06-01 08:12 UTC, WrathChaos commented
>  Screen.Recording.2021-06-01.at.09.55.40.mov

The second password is not secure text. Can you fix it?

2021-06-01 08:24 UTC, WrathChaos approved these changes, later dismissed

2021-06-01 08:51 UTC, WrathChaos approved these changes

2021-06-07 17:11 UTC, merged